apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  sources:
    # - repoURL: https://github.com/Yannik26/argo-secrets.git
    #   path: infra/argocd
    #   targetRevision: HEAD
    # - repoURL: https://github.com/Yannik26/argo-infrastructure.git
    #   path: infra/argocd
    #   targetRevision: HEAD
    - chart: argo-cd
      repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 7.6.12 # Replace with the Longhorn version you'd like to install or upgrade to
      helm:
        values: |
          global:
            domain: "argocd.yannikmueller.eu"
            deploymentStrategy:
              type: RollingUpdate
              rollingUpdate:
                maxSurge: 25%
                maxUnavailable: 25%
          configs:
            cm:
              exec.enabled: true
            params:
              server.insecure: false
          redis:
            image:
              repository: redis
              tag: 7.4-alpine
          server:
            autoscaling:
              enabled: true
            certificate:
              enabled: true
              issuer:
                group: "cert-manager.io"
                kind: "ClusterIssuer"
                name: "letsencrypt"
            ingress:
              enabled: true
              ingressClassName: "traefik"
              tls: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
