apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  sources:
    # - repoURL: https://github.com/Yannik26/argo-secrets.git
    #   path: infra/argocd
    #   targetRevision: HEAD
    - repoURL: https://github.com/Yannik26/argo-infrastructure.git
      path: infra/argocd
      targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
