apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
spec:
  project: default
  sources:
    # - repoURL: https://github.com/Yannik26/argo-secrets.git
    #   path: infra/argocd
    #   targetRevision: HEAD
    # - repoURL: https://github.com/Yannik26/argo-infrastructure.git
    #   path: infra/harbor
    #   targetRevision: HEAD
    - chart: harbor
      repoURL: https://helm.goharbor.io
      targetRevision: 1.16.2 # Replace with the harbor version you'd like to install or upgrade to
      helm:
        values: |
          expose:
            type: ingress
            tls:
              enabled: true
              certSource: secret
              secret:
                secretName: "harbor.yannikmueller.eu-tls"
            ingress:
              hosts:
                core: harbor.yannikmueller.eu
              className: traefik
              annotations:
                cert-manager.io/cluster-issuer: letsencrypt-staging
            externalURL: https://harbor.yannikmueller.eu
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
