apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: influxdb-service-redirect
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/Yannik26/argo-infrastructure.git
      path: infra/influxdb
      targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
