apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  sources:
    # - repoURL: https://github.com/Yannik26/argo-secrets.git
    #   path: infra/argocd
    #   targetRevision: HEAD
    # - repoURL: https://github.com/Yannik26/argo-infrastructure.git
    #   path: infra/argocd
    #   targetRevision: HEAD
    - chart: grafana
      repoURL: https://grafana.github.io/helm-charts
      targetRevision: 8.6.4 # Replace with the Prometheus version you'd like to install or upgrade to
      helm:
        releaseName: grafana
        values: |
          ingress:
            enabled: true
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt
            hosts:
            - grafana.yannikmueller.eu
            tls:
            - secretName: grafana.yannikmueller.eu-tls
              hosts:
                - grafana.yannikmueller.eu
          persistence:
            type: pvc
            enabled: true
            storageClassName: longhorn
    - chart: prometheus
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 26.0.0 # Replace with the Prometheus version you'd like to install or upgrade to
      helm:
        releaseName: prometheus
        values: |
          server:
            ingress: 
              enabled: true
              ingressClassName: traefik
              annotations:
                cert-manager.io/cluster-issuer: letsencrypt
              hosts:
              - prometheus.yannikmueller.eu
              tls:
              - secretName: prometheus.yannikmueller.eu-tls
                hosts:
                  - prometheus.yannikmueller.eu
            persistentVolume:
              enabled: true
              size: 16Gi
              storageClass: "longhorn"
            statefulSet:
              enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
