# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: zot
#   namespace: argocd
# spec:
#   project: default
#   sources:
#     # - repoURL: https://github.com/Yannik26/argo-secrets.git
#     #   path: infra/argocd
#     #   targetRevision: HEAD
#     # - repoURL: https://github.com/Yannik26/argo-infrastructure.git
#     #   path: infra/argocd
#     #   targetRevision: HEAD
#     - chart: zot
#       repoURL: http://zotregistry.dev/helm-charts
#       targetRevision: 0.1.66 # Replace with the zot version you'd like to install or upgrade to
#       helm:
#         values: |
#           service:
#             type: ClusterIP
#           ingress:
#             enabled: true
#             annotations:
#               cert-manager.io/cluster-issuer: letsencrypt
#             className: traefik
#             hosts:
#               - host: zot.yannikmueller.eu
#                 paths:
#                   - path: /
#             tls:
#               - secretName: zot.yannikmueller.eu-tls
#                 hosts:
#                   - zot.yannikmueller.eu
#           httpGet:
#             scheme: HTTP
#           persistence: true
#           pvc:
#             create: true
#             name: zot-pvc
#             storage: 20Gi
#             storageClassName: longhorn
#           configFiles:
#             config.json: |-
#               {
#               "storage": { "rootDirectory": "/var/lib/registry" },
#               "http": { "address": "0.0.0.0", "port": "5000" },
#               "log": { "level": "debug" }
#               }
#
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: zot
#   syncPolicy:
#     automated:
#       prune: true
#     syncOptions:
#       - CreateNamespace=true
