apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/Yannik26/argo-secrets.git
      path: network/cloudflared/
      targetRevision: HEAD
    - repoURL: https://github.com/Yannik26/argo-infrastructure.git
      path: network/cloudflared/
      targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
