apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: traefik
spec:
  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  project: default
  sources:
    - chart: traefik
      repoURL: https://traefik.github.io/charts
      targetRevision: 30.0.2
      helm:
        values: |
          providers:
            kubernetesIngress:
              publishedService:
                enabled: true
              ingressEndpoint:
                publishedService: "traefik/traefik"

  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
