apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: traefik
spec:
  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  project: default
  sources:
    - chart: traefik
      repoURL: https://traefik.github.io/charts
      targetRevision: 34.4.0
      helm:
        values: |
          ingressRoute:
            dashboard:
              enabled: true
          providers:
            kubernetesIngress:
              publishedService:
                enabled: true
              ingressEndpoint:
                publishedService: "traefik/traefik"
          ports:
            web:
              redirections:
                entryPoint:
                  to: websecure

  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
