apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: traefik
spec:
  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  project: default
  sources:
    - chart: traefik
      repoURL: https://traefik.github.io/charts
      targetRevision: 35.2.0
      helm:
        values: |
          annotations:
            keel.sh/policy: minor
            keel.sh/trigger: poll
            keel.sh/pollSchedule: "@daily"
          ingressRoute:
            dashboard:
              enabled: true
          providers:
            kubernetesIngress:
              publishedService:
                enabled: true
              ingressEndpoint:
                publishedService: "traefik/traefik"
          # ports:
          #   web:
          #     redirections:
          #       entryPoint:
          #         to: websecure
          #         scheme: https

  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
