apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: metallb
spec:
  destination:
    namespace: metallb-system
    server: https://kubernetes.default.svc
  project: default
  source:
    - chart: metallb
      repoURL: https://metallb.github.io/metallb
      targetRevision: 0.14.8
    # - repoURL:
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true

