apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # annotations:
  #   argocd-image-updater.argoproj.io/image-list: vaultwarden-server=vaultwarden/server:latest
  #   argocd-image-updater.argoproj.io/vaultwarden-server.update-strategy: digest
  #   argocd-image-updater.argoproj.io/vaultwarden-server.force-update: "true"
  name: gitlab
  namespace: argocd
spec:
  project: default
  sources:
    # - repoURL: https://github.com/Yannik26/argo-secrets.git
    #   path: apps/gitea/
    #   targetRevision: HEAD
    - repoURL: https://github.com/Yannik26/argo-infrastructure.git
      path: apps/gitea/
      targetRevision: HEAD
    # - chart: vaultwarden
    #   repoURL: https://dl.gitea.com/charts/
    #   targetRevision: 0.31.2 # Replace with the cert-manager version you'd like to install or upgrade to
    #   helm:
    #     values: |
    #       gitea:
    #         config:

  destination:
    server: https://kubernetes.default.svc
    namespace: gitlab
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
