apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: mealie=ghcr.io/mealie-recipes/mealie:latest
    argocd-image-updater.argoproj.io/mealie.update-strategy: digest
    argocd-image-updater.argoproj.io/mealie.force-update: "true"
  name: mealie
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/Yannik26/argo-secrets.git
      path: apps/mealie/
      targetRevision: HEAD
    - repoURL: https://github.com/Yannik26/argo-infrastructure.git
      path: apps/mealie/
      targetRevision: HEAD

  destination:
    server: https://kubernetes.default.svc
    namespace: mealie
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
