apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: paperless
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/Yannik26/argo-secrets.git
      path: apps/paperless/
      targetRevision: HEAD
    - repoURL: https://github.com/Yannik26/argo-infrastructure.git
      path: apps/paperless/
      targetRevision: HEAD
    - chart: tika
      repoURL: https://apache.jfrog.io/artifactory/tika
      targetRevision: 2.9.0 # Replace with the tika version you'd like to install or upgrade to
      helm:
        releaseName: tika
        values: |
          service:
            type: ClusterIP
            port: 9998
          resources:
            requests:
              cpu: "100m"
              memory: "500Mi"
  destination:
    server: https://kubernetes.default.svc
    namespace: paperless
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
