apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sds-status
  namespace: argocd
spec:
  project: default
  sources:
    # - repoURL: https://github.com/Yannik26/argo-secrets.git
    #   path: apps/vaultwarden/
    #   targetRevision: HEAD
    # - repoURL: https://github.com/Yannik26/argo-infrastructure.git
    #   path: apps/vaultwarden/
    #   targetRevision: HEAD
    - chart: nats
      repoURL: https://nats-io.github.io/k8s/helm/charts/
      targetRevision: 1.2.6 # Replace with the nats version you'd like to install or upgrade to
      helm:
      releaseName: nats
        # values: |
        #   # image:


  destination:
    server: https://kubernetes.default.svc
    namespace: sds-status
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
