apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: spoolman=ghcr.io/donkie/spoolman:latest
    argocd-image-updater.argoproj.io/spoolman.update-strategy: digest
    argocd-image-updater.argoproj.io/spoolman.force-update: "true"
  name: spoolman
  namespace: argocd
spec:
  project: default
  sources:
    # - repoURL: https://github.com/Yannik26/argo-secrets.git
    #   path: apps/spoolman/
    #   targetRevision: HEAD
    - repoURL: https://github.com/Yannik26/argo-infrastructure.git
      path: apps/spoolman/
      targetRevision: HEAD

  destination:
    server: https://kubernetes.default.svc
    namespace: spoolman
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
