apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/Yannik26/argo-secrets.git
      path: apps/vaultwarden/
      targetRevision: HEAD
    - repoURL: https://github.com/Yannik26/vaultwarden-helm/
      path: charts/vaultwarden/
      helm:
        values: |
          image:
            tag: "1.32.0"
          adminToken:
            existingSecret: ""
            existingSecretKey: ""
          domain: "https://vault-test.yannikmueller.eu"
          signupsAllowed: false
          signupDomains: "yannik-mueller.de"
          invitationsAllowed: true
          websocket:
            enabled: false
          pushNotifications:
            existingSecret: push-secret
            installationId:
              existingSecretKey: "id"
            installationKey:
              existingSecretKey: "key"
            relayUri: "https://api.bitwarden.eu"
            identityUri: "https://identity.bitwarden.eu"
          ingress:
            enabled: true
            hostname: vault-test.yannikmueller.eu
            class: "traefik"
            nginxIngressAnnotations: true
            additionalAnnotations:
                cert-manager.io/cluster-issuer: letsencrypt-staging
            labels: {}
            tls: true
            tlsSecret: "vault-test.yannikmueller.eu-tls"
            path: "/"
            pathWs: "/notifications/hub"
            pathType: "Prefix"
            pathTypeWs: "Exact"
          database:
            type: "default"
          smtp:
            host: "smtp.goneo.de"
            from: "vaultwarden@yannik-mueller.de"
            fromName: "Vaultwarden"
            existingSecret: "vw-secret"
            security: "force_tls"
            port: 465
            username:
              existingSecretKey: "smtp-username"
            password:
              existingSecretKey: "smtp-password"
            authMechanism: "Login"
            debug: false
          data:
            name: "vaultwarden-data"
            size: "20Gi"
            class: "longhorn"
            path: "/data"
          storage:
            enabled: true
            size: "15Gi"
            class: "longhorn"
            dataDir: "/data"

  destination:
    server: https://kubernetes.default.svc
    namespace: vaultwarden-test
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
